name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build AMD64 Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/dcgm-container-mapper-linux-amd64 main.go
          chmod +x dist/dcgm-container-mapper-linux-amd64

      - name: Build ARM64 Binary
        run: |
          GOOS=linux GOARCH=arm64 go build -o dist/dcgm-container-mapper-linux-arm64 main.go
          chmod +x dist/dcgm-container-mapper-linux-arm64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/dcgm-container-mapper-linux-amd64
            dist/dcgm-container-mapper-linux-arm64
          draft: false
          prerelease: false
          generate_release_notes: true 